name: Deploy Staging

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: Setup languages
        uses: ./.github/actions/setup-languages
      - name: Vendor gems
        run: bundle cache --all
      - name: Precompile assets
        env:
          RAILS_ENV: staging
          SECRET_KEY_BASE: not-actually-secret
        run: bundle exec rake assets:precompile

      - name: Deploy app
        uses: 18F/cg-deploy-action@main
        env:
          RAILS_MASTER_KEY: ${{ secrets.STAGING_RAILS_MASTER_KEY }}
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: sandbox-gsa
          cf_space: matt.hinz
          push_arguments: "--vars-file config/deployment/staging.yml --var rails_master_key=$RAILS_MASTER_KEY"
